In [2]:
import numpy as np

# Sigmoid Activation Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# Input Dataset (XOR)
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Expected Output
y = np.array([[0], [1], [1], [0]])

# Random seed for reproducibility
np.random.seed(42)

# Network Architecture
input_neurons = 2
hidden_neurons = 3
output_neurons = 1

# Initialize weights and biases
W1 = np.random.uniform(size=(input_neurons, hidden_neurons))
b1 = np.random.uniform(size=(1, hidden_neurons))

W2 = np.random.uniform(size=(hidden_neurons, output_neurons))
b2 = np.random.uniform(size=(1, output_neurons))

# Training parameters
learning_rate = 0.1
epochs = 10000

# Training loop
for epoch in range(epochs):

    # Forward Propagation
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    predicted_output = sigmoid(final_input)

    # Error
    error = y - predicted_output

    # Backpropagation
    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights and biases
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate


# ===== FINAL OUTPUT =====

print("\nFinal Predicted Output:")
print(predicted_output)

print("\nRounded Predictions (0 or 1):")
print(np.round(predicted_output).astype(int))

print("\nExpected Output:")
print(y)


Final Predicted Output:
[[0.05009215]
 [0.92079488]
 [0.90354216]
 [0.10615431]]

Rounded Predictions (0 or 1):
[[0]
 [1]
 [1]
 [0]]

Expected Output:
[[0]
 [1]
 [1]
 [0]]
